### ISSUE TITLE
Improve image

### ISSUE THREAD

**Issue by brandonkal** [CharlesChiuGit/Logseq-Git-Sync-101#15]
The README image uses the word "iCloud" in place of Syncthing under "Syncthing Warnings"

You should also add that unlike a centralized git setup or iCloud, Syncthing is P2P. Which is nice from a privacy perspective and generally means a faster sync (especially with PDFs and images). But it also means both devices must be online at the same time for a sync to occur unless the user adds a server.

**Comment by CharlesChiuGit** [comment]
I aware of the typo in the image, but the image author havn't response to me yet.

I understand the nice P2P property of Syncthing, but since the repo is generally for the newbies, I don't think it's a good idea. Some people are already having a hard time implement this workflow, I would rather put less irrelevant informations. But you're welcome to put a brief introduction in [discussions](https://github.com/CharlesChiuGit/Logseq-Git-Sync-101/discussions), I'll pin it!

Close it for now, feel free to reopen it.

**Comment by CharlesChiuGit** [comment]
@brandonkal Image updated. Please [take a look](https://github.com/CharlesChiuGit/Logseq-Git-Sync-101/blob/main/src/self-managed-sync-v2.png).
